package com.mayandro.local.utils

object DbConstants {

    const val DATABASE_NAME = "corona.db"

    const val CORONA_GLOBAL_SUMMARY_TABLE = "corona_global_summary_table"
    const val CORONA_COUNTRY_SUMMARY_TABLE = "corona_countries_summary_table"

    // GLOBAL SUMMARY TABLE
    const val QUERY_GET_ALL_GLOBAL_SUMMARY = "SELECT * FROM $CORONA_GLOBAL_SUMMARY_TABLE"

    const val QUERY_GET_ALL_GLOBAL_SUMMARY_BY_DATE = "SELECT * FROM $CORONA_GLOBAL_SUMMARY_TABLE WHERE date = :date"

    const val QUERY_LAST_GLOBAL_SUMMARY =  "SELECT * FROM $CORONA_GLOBAL_SUMMARY_TABLE ORDER BY date DESC LIMIT 1"

    const val DELETE_GLOBAL_SUMMARY = "DELETE FROM $CORONA_GLOBAL_SUMMARY_TABLE"


    //COUNTRIES TABLE
    const val QUERY_GET_ALL_COUNTRIES_SUMMARY = "SELECT * FROM $CORONA_COUNTRY_SUMMARY_TABLE"

    const val DELETE_ALL_COUNTRIES_SUMMARY = "DELETE FROM $CORONA_COUNTRY_SUMMARY_TABLE"

    const val GET_COUNTRY_SUMMARY_BY_ID = "SELECT * FROM $CORONA_COUNTRY_SUMMARY_TABLE WHERE id = :id"

    const val GET_COUNTRY_SUMMARY_BY_COUNTRY = "SELECT * FROM $CORONA_COUNTRY_SUMMARY_TABLE WHERE country = :country"

    const val GET_COUNTRY_SUMMARY_BY_COUNTRY_CODE = "SELECT * FROM $CORONA_COUNTRY_SUMMARY_TABLE WHERE countryCode = :countryCode"

}